# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for Linux and macOS"
  homepage "https://github.com/geodro/lerd"
  version "1.21.1"
  license "MIT"

  depends_on "podman"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geodro/lerd/releases/download/v1.21.1/lerd_1.21.1_darwin_amd64.tar.gz"
    sha256 "caa24b9e5ff51df801fd065693ce29de20bb85eb44c14b1e3adfa48a80e78c51"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geodro/lerd/releases/download/v1.21.1/lerd_1.21.1_darwin_arm64.tar.gz"
    sha256 "da3e020758296f3d4fe27386111500d5a3d815926f8374fccb1a5c3ee7ce92d2"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end

  def caveats
    <<~EOS
      To finish setting up Lerd, run:
        lerd install

      To uninstall cleanly, run in order:
        lerd uninstall
        brew uninstall lerd

      If you already removed the binary before running `lerd uninstall`, run:
        ~/.local/bin/lerd-cleanup
        brew uninstall lerd
    EOS
  end
end
