# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for Linux and macOS"
  homepage "https://lerd.sh"
  version "1.34.3"
  license "MIT"

  depends_on "podman" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lerd-env/lerd/releases/download/v1.34.3/lerd_1.34.3_darwin_amd64.tar.gz"
      sha256 "e1dcfa6ea1ad00453db05c398c3362da3bfe3ff1dc995ea07f544b6e27698b72"

      define_method(:install) do
        bin.install "lerd"
        bin.install "lerd-tray" if File.exist?("lerd-tray")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lerd-env/lerd/releases/download/v1.34.3/lerd_1.34.3_darwin_arm64.tar.gz"
      sha256 "b1e5d3720b4739a193b093df8230a43639db333a82a11a15f632b14919c53ca2"

      define_method(:install) do
        bin.install "lerd"
        bin.install "lerd-tray" if File.exist?("lerd-tray")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lerd-env/lerd/releases/download/v1.34.3/lerd_1.34.3_linux_amd64.tar.gz"
      sha256 "f216e53def5f3f87d8ff66874200e97c200033ab92a3b1bb643eed5338b6fb33"
      define_method(:install) do
        bin.install "lerd"
        bin.install "lerd-tray" if File.exist?("lerd-tray")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lerd-env/lerd/releases/download/v1.34.3/lerd_1.34.3_linux_arm64.tar.gz"
      sha256 "d690e6ca48691cd82d9032e893c614f76ae161771901be7e5648a4fd9e1349f8"
      define_method(:install) do
        bin.install "lerd"
        bin.install "lerd-tray" if File.exist?("lerd-tray")
      end
    end
  end

  def post_install
    # brew runs this inside a read-only mount namespace with HOME pointed at
    # a throwaway directory, and everything the repair touches lives in the
    # real home. On Linux the user's own systemd manager runs it outside that
    # namespace; elsewhere the direct call is all there is to try.
    if OS.linux?
      quiet_system "/bin/sh", "-c",
        "XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)} systemd-run --user --quiet --collect --wait " \
        "--unit=lerd-post-upgrade #{bin}/lerd post-upgrade"
    else
      require "etc"
      with_env(HOME: Etc.getpwuid(Process.uid).dir, XDG_CONFIG_HOME: nil, XDG_DATA_HOME: nil) do
        quiet_system bin/"lerd", "post-upgrade"
      end
    end
  end

  def caveats
    <<~EOS
      To finish setting up Lerd, run:
        lerd install

      To uninstall cleanly, run in order:
        lerd uninstall
        brew uninstall lerd

      If you already removed the binary before running `lerd uninstall`, run:
        ~/.local/bin/lerd-cleanup
        brew uninstall lerd
    EOS
  end
end
