# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lerd < Formula
  desc "Local Laravel development environment for Linux and macOS"
  homepage "https://github.com/geodro/lerd"
  version "1.19.3"
  license "MIT"

  depends_on "podman"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/geodro/lerd/releases/download/v1.19.3/lerd_1.19.3_darwin_amd64.tar.gz"
    sha256 "20e9e6935f49fd4ecec4e9566faa1ae4e73e3fd0bf001726e5bdbadd7ae5d2ec"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/geodro/lerd/releases/download/v1.19.3/lerd_1.19.3_darwin_arm64.tar.gz"
    sha256 "c98dca780a46316281932472ebcf27b4295c49f40d514d0e27fedd2fc500b172"

    define_method(:install) do
      bin.install "lerd"
      bin.install "lerd-tray" if File.exist?("lerd-tray")
    end
  end

  def caveats
    <<~EOS
      To finish setting up Lerd, run:
        lerd install

      To uninstall cleanly, run in order:
        lerd uninstall
        brew uninstall lerd

      If you already removed the binary before running `lerd uninstall`, run:
        ~/.local/bin/lerd-cleanup
        brew uninstall lerd
    EOS
  end
end
